name: master branch workflow
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  run:
    name: run
    runs-on: ubuntu-18.04
    steps:
    - name: exec
      uses: ./

    - name: show
      run: git config --global -l

